<?php
return array(
    'learn/(er|re)/([0-9]+)' => 'learning/index/$1/$2',
    'api/word/update' => 'wordAPI/update',
    'api/word/add' => 'wordAPI/add',
    'api/word/delete' => 'wordAPI/delete',
    'word/update/([0-9]+)' => 'word/update/$1',
    'api/dictionary/setrows' => 'dictionaryAPI/setRowsNumber',
    'api/dictionary/add' => 'dictionaryAPI/addDictionaryToUser',
    'api/dictionary/create' => 'dictionaryAPI/create',
    'api/dictionary/update' => 'dictionaryAPI/update',
    'dictionary/update/([0-9]+)' => 'dictionary/update/$1',
    'dictionary/create' => 'dictionary/create',
    'dictionary/add' => 'dictionary/add',
    'dictionary/edit/([0-9]+)/([0-9]+)' => 'dictionary/editWord/$1/$2',
    'dictionary/remove/([0-9]+)' => 'dictionary/removeDictionary/$1',
    'dictionary/delete/([0-9]+)' => 'dictionary/deleteDictionary/$1',
    'dictionary/([0-9]+)' => 'dictionary/data/$1',
    'api/registration' => 'authregAPI/registration',
    'api/login' => 'authregAPI/login',
    'api/reset/newpass' => 'authregAPI/newpass',
    'api/reset' => 'authregAPI/reset',
    'reset/([A-Za-z0-9]+)' => 'authreg/newpass/$1',
    'reset' => 'authreg/reset',
    'login' => 'authreg/login',
    'logout' => 'authreg/logout',
    'registration' => 'authreg/registration',
    'profile' => 'profile/index',
);